### ISSUE TITLE
bug(blog): Reader mode is not available on some websites

### ISSUE THREAD

**Issue by huyng12** [thien-do/memos.pub#11]
Safari on iPhone X (iOS 15.3.1)

![image](https://user-images.githubusercontent.com/66771508/157636519-55f03c60-6392-475c-8db1-38a4f10363a9.png)

**Comment by thien-do** [comment]
Some actually works, but this one doesn't:

https://hieuk09.memos.pub/place_i_know/vietnam/hanoi/readme.md

**Comment by thien-do** [comment]
After a while, this is quite unstable to reproduce so I'll close it for now
