### ISSUE TITLE
bug: "Go home" link in page 404

### ISSUE THREAD

**Issue by kcjpop** [thien-do/memos.pub#29]
### What

![image](https://user-images.githubusercontent.com/172503/163169144-a2a3f403-cce3-4fce-8755-581caaa69924.png)

Example: https://notes.ancaois.me/notes/404

Currently "Go home" in page 404 is linked to https://memos.pub/. It should be linked to the hosted homepage, e.g. https://notes.ancaois.me in this case.

**Comment by thien-do** [comment]
Hi @kcjpop thanks for reporting this issue. This is a serious issue as we commit to not having any reference to "memos.pub" in our members' pages.

This has been fixed: https://notes.ancaois.me/acbc

<img width="1024" alt="Screen Shot 2022-04-14 at 11 41 26" src="https://user-images.githubusercontent.com/5953369/163314947-4607b792-a040-490a-b45e-bcb8d5edb792.png">

If you are interested in the fix:

- 9a16c852f9abecbdf951b9f806744568340619eb to avoid exposing the path to your source repo
- 6a1adb5e2fa9271bb6f98273a27066373c94d15d to remove memos.pub references in error pages (in case of membership)
