### ISSUE TITLE
feat(blog): Add loading indicator

### ISSUE THREAD

**Issue by monodyle** [thien-do/memos.pub#32]
I navigate from [this site](https://ruanyf.memos.pub/weekly/docs) to the article inside, but the waiting time so long, a little confused about is this page being navigated?

I think adding a loading icon or process bar will get a better experience for users.

**Comment by thien-do** [comment]
yep that is right. On first visit (after a new deployment) it takes significant time to load (before it is cached). Let me try to look into skeleton or process bar to reduce this.
